# -*- coding: utf-8 -*-
"""Penugasan week 4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1sFn-4rAThRgpcPqwbK32LG_RHRUMOo8r

#SESUAIKAN DENGAN DATASET YANG DIBERIKAN PANITIA YA!
"""

import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

import warnings
warnings.filterwarnings('ignore')

"""# Eksplorasi dataset

Untuk datasetnya bisa kalian download [disini](https://drive.google.com/file/d/1Xts94adrcUeCs76h_5tzM7Zttu9jjU0c/view)

Muat dataset kalian ke sebuah dataframe menggunakan fungsi `read_csv()` pada pandas

Contoh:
`data = pd.read_csv('/content/AB_NYC_2019.csv')`
"""

data = pd.read_csv('/content/drive/MyDrive/Data Analyst Bootcamp/customer_data.csv')

data

"""Tampilkan jumlah baris dan kolom dari dataset tadi menggunakan fungsi `shape`"""



"""Contoh: `data.shape`"""

# Masukkan kode kalian disini
data.shape

"""Tampilkan data pada 10 baris pertama menggunakan fungsi `head(jumlah_bari_yang_ingin_ditampilkan)`

Contoh: `data.head(5)`
"""

# Masukkan ko kalian disini
data.head(5)

"""# Pengecekan nilai kosong

Lihat informasi pada dataset kalian menggunakan fungsi `info()`

Contoh: `data.info()`
"""

# Masukkan kode kalian disini
data.info()

"""Hitung jumlah data yang memiliki missing value pada setiap kolom menggunakan fungsi `isna` dan fungsi `sum()`

Contoh: `data.isna().sum()`
"""

# Masukkan kode kalian disini
data.isna().sum()

"""Hitung proporsi missing value pada setiap kolom

Contoh: `(data.isna().sum() / data.shape[0]) * 100`
"""

# Masukkan kode kalian disini
(data.isna().sum()/data.shape[1]) *50

"""Tampilkan beberapa data dengan melakukan filter yang hanya menampilkan baris yang memiliki nilai null

Contoh: `data[data['kolom_yang_ingin_ditampilkan'].isna()].head(10)`

Pada kasus ini tampilkan kolom price
"""

# Masukkan kode kalian disini
data['Income']

data[data['Income'].isna()].head(10)

"""Dengan adanya missing value pada kolom price kita bisa kita bisa melakukan penghapusan data atau mengisi data tersebut untuk tahap analisa lebih lanjut

Jumlah missing data pada kolom price sekitar 1.03%. Jika kita menghapus semua baris yang memiliki nilai price yang hilang, hal ini dapat mengubah distribusi harga dan mendistorsi analisis lebih lanjut. Oleh karena itu, kita akan menggunakan metode imputasi dengan median untuk menangani missing value pada kolom ini. Proses ini akan dilakukan pada bagian imputasi missing value.

# Pembersihan data

## Pengecekan duplikasi

Lakukan pengecekan yang terindikasi duplikat pada dataset kita. Gunakan fungsi `duplicated()` dan `sum()`

Contoh: `print(f"Jumlah data duplikat: {data.duplicated().sum()}")`
"""

# Masukkan kode kalian disini
print(f"Jumlah data duplikat: {data.duplicated().sum()}")

"""Hapus data duplikat tersebut.

Contoh: `data = data.drop_duplicates().reset_index(drop=True)`
"""

# Masukkan kode kalian disini
data = data.drop_duplicates().reset_index(drop=True)

"""Cek lagi apakah sudah berhasil menghapus data duplikat."""

# Masukkan kode kalian disini
data = data.drop_duplicates().reset_index(drop=True)

"""## Pengecekan kolom neighbourhood_group

Cek isi dari kolom neighbourhood_group yang menggunakan fungsi `unique()`

Contoh: `data['nama_kolom'].unique()`
"""

# Masukkan kode kalian disini
data['Income'].unique()

"""Lihat juga jumlah untuk setiap value menggunakan fungsi `value_counts()`

Contoh: `data['nama_kolom'].value_counts()`
"""

# Masukkan kode kalian disini
data['Income'].value_counts()

"""Karena pada kolom neighbourhood_group ketidakkonsistenan ejaan maka kita replace dengan ejaan yang benar

Lakukan penggantian ejaan agar sesuai dengan ejaan berikut ini: Bronx, Brooklyn, dan Queens.

Contoh kode: `data['nama_kolom'] = data['nama_kolom'].replace({
    'Kata_yang_ingin_diganti': 'ejaan_yang_benar'
})`
"""

# Masukkan kode kalian disini
data['Dt_Customer'] = data['Dt_Customer'].replace({ '9/42012': '10/2/2022' })

"""Cek lagi apakah sudah diubah dengan benar. Gunakan fungsi `value_counts()` atau `unique()`"""

# Masukkan kode kalian disini

"""# Imputasi / Mengisi missing values

Sebelum kita mulai mari kita cek distribusi setiap kolom

Contoh: `plt.hist(data['nama_kolom'], density=True, bins=100)`

Tanpilkan grafik distribusi pada kolom price
"""

# Masukkan kode kalian disini
plt.hist(data['Income'], density=True,bins=100)

"""Tampilkan grafik distribusi untuk kolom minimum_nights"""

# Masukkan kode kalian disini
plt.hist(data['ID'], density = True, bins = 100)

"""Tampilkan grafik distribusi untuk kolom availability_365"""

# Masukkan kode kalian disini
plt.hist(data['Education'], density = True)

"""Tampilkan grafik distribusi untuk kolom number_of_reviews"""

# Masukkan kode kalian disini
plt.hist(data['Year_Birth'], density = True, bins = 100)

"""Tampilkan grafik distribusi untuk kolom reviews_per_month"""

# Masukkan kode kalian disini
plt.hist(data['NumWebPurchases'], density=True, bins=100)

"""Terlihat bahwa histogram price, number_of_riviews, dan riviews_per_month memiliki skewness yang positif atau terdapat extreme values/outlier. Artinya kita perlu juga nanti mengatasi outlier pada kolom tersebut. Namun untuk saat ini, mari kita isi missing value di kolom price, number_of_riviews, dan riviews_per_month menggunakan median dari ketiga kolom tersebut

Hitung median dari masing-masing kolom menggunakan fungsi `median()`

Contoh:

```
nama_variabel = data[nama_kolom].median()
print(f"Median nama_kolom: {nama_variabel}")
```

Median kolom price
"""

# Masukkan kode kalian disini
data.describe()



tengah = data['Income'].median()
print(f"Median Income: {tengah}")
print("Median Income: ", tengah)

"""Median kolom number_of_reviews"""

# Masukkan kode kalian disini
plt.hist(data['Dt_Customer'], density = True)

"""Median kolom reviews_per_month"""

# Masukkan kode kalian disini
plt.hist(data['Recency'], density = True, bins = 100)

"""Kemuadian lakukan imputasi untuk mengisi missing value pada setiap kolom

Contoh:

```
data['nama_kolom'] = data['nama_kolom'].fillna(variabel_median)
```

Imputasi kolom price
"""

# Masukkan kode kalian disini
data['Income'] = data['Income'].fillna(10)

"""Imputasi kolom number_of_reviews"""

# Masukkan kode kalian disini
data['Income'] = data['Income'].fillna(10)

"""Imputasi kolom reviews_per_month"""

# Masukkan kode kalian disini
data['Income'] = data['Income'].fillna(10)

"""Kemudian cek jumlah missing value setelah melakukan imputasi menggunakan fungsi `isna()` dan `sum()`"""

# Masukkan kode kalian disini
data['Income'] = data['Income'].fillna(10)

"""# Mengatasi outlier

Kita akan menggunakan metode IQR untuk memeriksa nilai-nilai outlier pada data, khususnya pada kolom price, number_of_reviews, dan reviews_per_month. Untuk mempermudah analisis dan pengerjaan, kita akan membuat fungsi yang dapat menerima input berupa nama kolom serta opsi apakah kita ingin menghitung upper bound atau lower bound.

Berikut contoh fungsi untuk cek outlier menggunakan metode IQR.

```
def cek_outlier(nama_kolom, batas):
  Q1 = np.percentile(data[nama_kolom], 25,
                     interpolation = 'midpoint')

  Q3 = np.percentile(data[nama_kolom], 75,
                     interpolation = 'midpoint')

  IQR = Q3 - Q1

  if batas == 'upper_bound':
      bound = np.where(data[nama_kolom] >= (Q3 + 1.5*IQR))
  elif batas == 'lower_bound':
      bound = np.where(data[nama_kolom] <= (Q1 - 1.5*IQR))
  return list(bound[0])
  ```
"""

# Masukkan kode kalian disini
def cek_outlier(nama_kolom, batas):
  Q1 = np.percentile(data[Income], 25,
                     interpolation = 'midpoint')

  Q3 = np.percentile(data[nama_kolom], 75,
                     interpolation = 'midpoint')

  IQR = Q3 - Q1

  if batas == 'upper_bound':
      bound = np.where(data[nama_kolom] >= (Q3 + 1.5*IQR))
  elif batas == 'lower_bound':
      bound = np.where(data[nama_kolom] <= (Q1 - 1.5*IQR))
  return list(bound[0])

"""Jalankan fungsi tadi untuk mendaptkan index data yang merupakan outlier

Contoh:

```
batas_atas/bawah_nama_kolom = cek_outlier('nama_kolom', 'upper_bound/lower_bound')
print(f"Jumlah total outlier : {len(batas_atas) + len(batas_bawah)}")
```

Untuk kolom price
"""

# Masukkan kode kalian disini
batas_atas/bawah_nama_kolom = cek_outlier('nama_kolom', 'upper_bound/lower_bound')
print(f"Jumlah total outlier : {len(batas_atas) + len(batas_bawah)}")

"""Untuk kolom number_of_reviews"""

# Masukkan kode kalian disini
batas_atas/bawah_nama_kolom = cek_outlier('nama_kolom', 'upper_bound/lower_bound')
print(f"Jumlah total outlier : {len(batas_atas) + len(batas_bawah)}")

"""Untuk kolom reviews_per_month"""

# Masukkan kode kalian disini
batas_atas/bawah_nama_kolom = cek_outlier('nama_kolom', 'upper_bound/lower_bound')
print(f"Jumlah total outlier : {len(batas_atas) + len(batas_bawah)}")

"""Kita akan membuat fungsi untuk menerima input sebuah dataframe dan juga nama kolom untuk filter / menghapus data outlier

Berikut kodenya:
```
def filter_outlier(df, nama_kolom):
    if nama_kolom == 'price':
        data_temp = df.loc[~df.index.isin(upper_price)]
        data_temp = data_temp.loc[~data_temp.index.isin(lower_price)]
        return data_temp
    if nama_kolom == 'number_of_reviews':
        data_temp = df.loc[~df.index.isin(upper_number_of_reviews)]
        data_temp = data_temp.loc[~data_temp.index.isin(lower_number_of_reviews)]
        return data_temp
    if nama_kolom == 'reviews_per_month':
        data_temp = df.loc[~df.index.isin(upper_reviews_per_month)]
        data_temp = data_temp.loc[~data_temp.index.isin(lower_reviews_per_month)]
        return data_temp
```
"""

# Masukkan kode kalian disini
def filter_outlier(df, nama_kolom):
    if nama_kolom == 'price':
        data_temp = df.loc[~df.index.isin(upper_price)]
        data_temp = data_temp.loc[~data_temp.index.isin(lower_price)]
        return data_temp
    if nama_kolom == 'number_of_reviews':
        data_temp = df.loc[~df.index.isin(upper_number_of_reviews)]
        data_temp = data_temp.loc[~data_temp.index.isin(lower_number_of_reviews)]
        return data_temp
    if nama_kolom == 'reviews_per_month':
        data_temp = df.loc[~df.index.isin(upper_reviews_per_month)]
        data_temp = data_temp.loc[~data_temp.index.isin(lower_reviews_per_month)]
        return data_temp

"""Buat dataframe baru dengan memanggil fungsi filter_outlier

Contoh:

```
nama_dataframe_baru = filter_outlier(dataframe_sebelumnya, 'nama_kolom')
print(nama_dataframe_baru.shape)
```

Dataframe baru dengan kolom price
"""

# Masukkan kode kalian disini
nama_dataframe_baru = filter_outlier(dataframe_sebelumnya, 'nama_kolom')
print(nama_dataframe_baru.shape)

"""Dataframe baru dengan kolom number_of_reviews"""

# Masukkan kode kalian disini
nama_dataframe_baru = filter_outlier(dataframe_sebelumnya, 'nama_kolom')
print(nama_dataframe_baru.shape)

"""Dataframe baru dengan kolom reviews_per_month"""

# Masukkan kode kalian disini
nama_dataframe_baru = filter_outlier(dataframe_sebelumnya, 'nama_kolom')
print(nama_dataframe_baru.shape)

"""Tampilkan beberapa data final dari dataframe terakhir menggunakan fungsi `head()`"""

# Masukkan kode kalian disini
nama_dataframe_baru = filter_outlier(dataframe_sebelumnya, 'nama_kolom')
print(nama_dataframe_baru.shape)

"""# Visualisasi data

Berikut ini adalah penugasan untuk memvisualisasikan dataframe terakhir kita

1. Buatlah histogram untuk memvisualisasikan distribusi pendapatan (Income) pelanggan.
"""

# Masukkan kode kalian disini

plt.hist(data['Income'], density = True, bins = 100)

"""2. Buatlah diagram batang untuk memvisualisasikan frekuensi pembelian melalui website (NumWebPurchases)."""

# Masukkan kode kalian disini
plt.hist(data['NumWebPurchases'], density = True, bins = 100)

"""3. Visualisasikan distribusi jumlah kunjungan bulanan ke website (NumWebVisitsMonth) menggunakan histogram."""

# Masukkan kode kalian disini
plt.hist(data['NumWebVisitsMonth'], density = True, bins = 100)

"""4. Buatlah diagram batang untuk memvisualisasikan jumlah pelanggan berdasarkan kategori Education (Pendidikan)."""

# Masukkan kode kalian disini
plt.hist(data['Education'], density=True, bins = 100)

"""5. Buatlah scatter plot untuk memvisualisasikan hubungan antara Recency (jumlah hari sejak transaksi terakhir) dengan NumStorePurchases (jumlah pembelian di toko)."""

# Masukkan kode kalian disini
plt.scatter(data['Recency'], data['NumStorePurchases'])